name: CI - Build Go, Push Docker, Update Manifest

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Golang app (binary)
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest .
          docker tag ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest \
                     ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:build-${{ github.run_number }}
          docker push ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          docker push ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:build-${{ github.run_number }}

      - name: Clone and update manifest repo
        run: |
          rm -rf golang-manifest
          git clone https://x-access-token:${{ secrets.GIT_PUSH_TOKEN }}@github.com/Danish1790/golang-manifest.git
          cd golang-manifest

          BUILD_TAG="build-${{ github.run_number }}"
          sed -i "s|image: .*$|image: danishasif/go-todo-assignment:${BUILD_TAG}|" golangSvc.yml

          git config user.name "danish1790"
          git config user.email "danish.asif.7190@gmail.com"

          git add golangSvc.yml
          git commit -m "Update image tag to ${BUILD_TAG}"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_PUSH_TOKEN }}@github.com/Danish1790/golang-manifest.git
          git push origin main

      - name: SSH, Pull & Run Container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          script: |
            sudo su
            cd ~/golang-manifest
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ vars.DOCKER_USERNAME }}" --password-stdin
            docker pull danishasif/go-todo-assignment:build-${{ github.run_number }}
            kubectl apply -f golangSvc.yml



      
