name: CI - Build Go, Push Docker, Update Manifest

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  build-push-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build Golang app (binary)
        run: |
          mkdir -p build
          GOOS=linux GOARCH=amd64 go build -o build/app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push Docker image
        run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest .
          docker tag ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest \
                     ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:build-${{ github.run_number }}
          docker push ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          docker push ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:build-${{ github.run_number }}

      - name: Clone and update manifest repo
        run: |
          git clone https://x-access-token:${{ secrets.GIT_PUSH_TOKEN }}@github.com/Danish1790/golang-manifest.git
          cd golang-manifest

          # Replace image tag with current build number
          sed -i 's|image: .*$|image: '"${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:build-${{ github.run_number }}"'|' golangSvc.yml

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add golangSvc.yml
          git commit -m "Update image tag to build-${{ github.run_number }}"
          git push origin main
